### ISSUE TITLE
call of overloaded ‘abs(long unsigned int)’ is ambiguous

### ISSUE THREAD

**Issue by lambdamoses** [bx3/Shannon_C_seq#1]
I can't build your package with `make`, since it gives an error: 

    /home/username/Shannon_Cpp_RNA_seq/src/Multi_graph_handler.cpp:876:52: error: call of overloaded ‘abs(long unsigned int)’ is ambiguous
             if(std::abs(diff+rmer_length-seq.size()) < 3)
                                                    ^
I'm using gcc 8.2.0, and have told CMake to use it. I can confirm this as the `make` log says things like
  
    /home/username/mylibs/include/c++/8.2.0/bits/std_abs.h:56:3: note: candidate: ‘long int std::abs(long int)’
       abs(long __i) { return __builtin_labs(__i); }
       ^~~
I suspect the culprit is `seq.size()`, since the `size` method of `string` returns `size_t`, which is unsigned. I reproduced the kind of `call to 'abs' is ambiguous` error by a minimum example:

    #include <cmath>
    #include <string>
    //[[Rcpp::export]]
    int foo(int x, std::string y) {
      return std::abs(x - y.size());
    }
This won't compile. Would you please fix this?

**Comment by bx3** [comment]
Thanks for reporting and all your analysis, and I think you are right on the sign/unsigned part. I have fixed it in my new update. In addition, the genome_ref_filter.h part is also fixed. 

Please give a try now.

**Comment by lambdamoses** [comment]
Thanks
