### ISSUE TITLE
fatal error: genome_ref_filter.h: No such file or directory

### ISSUE THREAD

**Issue by lambdamoses** [bx3/Shannon_C_seq#2]
I changed `seq.size()` into `static_cast<int>(seq.size())` in line 876 of src/Multi_graph_handler.cpp; this should fix issue #1, and the compilation went past that point, without any error or warnings. Then another error occurred:

    In file included from /home/username/Shannon_Cpp_RNA_seq/src/main.cpp:15:
    /home/username/Shannon_Cpp_RNA_seq/src/run_tasks.h:25:10: fatal error: genome_ref_filter.h: No such file or directory
     #include "genome_ref_filter.h"
              ^~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
Then I looked at your repo, and there indeed is no file `genome_ref_filter.h`.

**Comment by bx3** [comment]
You are right. I have commented that line. Thanks

**Comment by lambdamoses** [comment]
Thanks
